### ISSUE TITLE
Community Page - How big are User Profiles on main page

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#10]
On the community page, the individual user profile seems pretty large. Does it shrink when we add more people to it? How much?
![1-screenshot](https://user-images.githubusercontent.com/31212769/29625480-72a0eca2-87f1-11e7-903a-3d52e78faa2a.png)

**Comment by bbertucc** [comment]
I thought this was a bit too big. It scales to different browser sizes, but not when you add new users. This is something we can talk about in the meeting and maybe the YEP designers have ideas.
