### ISSUE TITLE
Community Page - Dot on Map Button

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#11]
There's a dot that appears on the Map Button, but it's not clear why it's there compared to the other buttons, which don't get dots if you click them.

![bukket_0_1-screenshot](https://user-images.githubusercontent.com/31212769/29627769-cf34d5f8-87f8-11e7-9f3f-227f9c2e1aee.png)

**Comment by bbertucc** [comment]
@raphaelgang - that map circle was by design. Maybe the design needs to updated? I wanted to set apart the "Map View" from the filter buttons some way. Does that make sense?

**Comment by bbertucc** [comment]
Changed dot to map icon

**Comment by raphaelgang** [comment]
this looks much better. Thanks!  





On Sat, Sep 9, 2017 7:21 AM, Blake Bertuccelli notifications@github.com  wrote:
Closed #11.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
