### ISSUE TITLE
Essentials/Tiny Pages: Pictures are small 

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#12]
For both circles and rectangle pictures, the pics seem small on both pages. 

![bukket_2_3-screenshot](https://user-images.githubusercontent.com/31212769/29628531-5fcf8cfa-87fb-11e7-9c07-21ec5894c9d1.png)
![bukket_3_4-screenshot](https://user-images.githubusercontent.com/31212769/29628535-61a40c40-87fb-11e7-9ec2-744747407a20.png)

**Comment by bbertucc** [comment]
@raphaelgang - this problem is resolved. You can checkout all the media styles at http://4pt0.decubing.com/media-styles/
