### ISSUE TITLE
What We Do - Font Size Consistency

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#13]
There's a couple of blocks where it looks like the fonts aren't the same size across the different sections. Is it possible to standardize this?
![font consistency](https://user-images.githubusercontent.com/31212769/29665030-c134b6d6-8897-11e7-945d-f3841b2c82c2.png)

**Comment by bbertucc** [comment]
We designed several different text layouts:
- Brief Body (< 300 char.)
- Regular Body (> 300 char. & < 800 Char)
- Regular Body with Paragraphs (> 300 char. & < 800 Char) 
- Long Body (> 800 char)
- Dual Column Body (text next to media)

The text size automatically adapts to be most readable in each layout.

So, if you added text under Stage 2, it would adapt to be a similar size to the text in the dual column.

Does that make sense?

-Bb.
