### ISSUE TITLE
Embedding Medium

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#14]
We'd like to embed our Medium blog to the website. Can we add it as a drop down on the menu bar at the top? We'd need to go through medium to set it up, but it doesn't look difficult. 

![image](https://user-images.githubusercontent.com/31212769/29665508-f2525140-8899-11e7-8bc9-1fe302c608f9.png)

Just wanted to flag it as a page to include. - https://help.medium.com/hc/en-us/articles/115005579728-Get-started-with-custom-domains

**Comment by bbertucc** [comment]
Yes. Totally. Send the me the new medium URL, and I'll add it. Also, I'll show you guys how to update the menu at our meeting.

**Comment by bbertucc** [comment]
Hey @raphaelgang - Did you set up the custom domain name, or is that something you need me to do?

**Comment by raphaelgang** [comment]
We thought more about it and decided to pass on it for now. We'll come back to
it at a later point. Would be great to have the external links open in new tabs
as an alternative.  





On Fri, Sep 8, 2017 4:28 PM, Blake Bertuccelli notifications@github.com  wrote:
Hey @raphaelgang  - Did you set up the custom domain name, or is that something
you need me to do?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by bbertucc** [comment]
K. I'm going to close the issue for now.

You can have menu links open in a new Window. In WordPress, under Appearance > Menu, click the Screen Options tab (pictured). There, you should be able to add a new option called "Link Target". You set links to open in a new window via this option.

![screen shot 2017-09-08 at 5 09 29 pm](https://user-images.githubusercontent.com/46652/30233024-963eba44-94b8-11e7-87c1-9da393bc11fc.png)
