### ISSUE TITLE
Homepage/Footer - Menu on the bottom

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#16]
To make it a little easier to navigate, we're thinking it might be helpful to have the menu on the similar to how camelback has it. Contact, Blog, About Us in the bottom left corner.

![image](https://user-images.githubusercontent.com/31212769/29665604-6dfec2a6-889a-11e7-8c23-65f663bb1fcf.png)

**Comment by bbertucc** [comment]
Definitely a good point. Would you want to keep the 4.0 tagline there too? We added that for Search Engine Optimization.

**Comment by raphaelgang** [comment]
If possible, yes, but if it it doesn't look good I'm fine with it not being there.

**Comment by bbertucc** [comment]
Closing this. Will announce footer/header on Issue #26.
