### ISSUE TITLE
Community/Test User Page - Clouds

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#18]
Are these pages where it's not possible to have the clouds? Our thought was just to keep it as consistent as possible. 

![image](https://user-images.githubusercontent.com/31212769/29665722-0c117a74-889b-11e7-94d1-b9697df18d64.png)

**Comment by bbertucc** [comment]
We have clouds in this page, in the quote area. Above the clouds, we've included a page header to the Venture and User Page. Checkout the attached screenshot of the Venture header. We found that if we put the header in the clouds, some of the text isn't readable. Happy to discuss more.

![screen shot 2017-08-24 at 10 13 31 am](https://user-images.githubusercontent.com/46652/29673474-e922f56e-88b4-11e7-9bb2-1152de14505f.png)
