### ISSUE TITLE
Mobile Rendering on Chrome

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#19]
It's not rendering nearly as cleanly as it did in the first version. This is in a chrome browser.

![image](https://user-images.githubusercontent.com/31212769/29665972-0809b62a-889c-11e7-98bb-8d5b23d9e7c9.png)

![image](https://user-images.githubusercontent.com/31212769/29665987-157b1498-889c-11e7-97d1-b0752ffb10b4.png)

**Comment by bbertucc** [comment]
@raphaelgang - Should be fixed!
