### ISSUE TITLE
Text size changes when viewing on safari 

### ISSUE THREAD

**Issue by breleha** [4pt0/4pt0-theme#20]
<img width="1440" alt="screen shot 2017-08-25 at 11 15 29 am" src="https://user-images.githubusercontent.com/31285256/29722515-b8bbde2c-8986-11e7-9095-286f9e7b76fb.png">

**Comment by bbertucc** [comment]
Should be resolved now. http://4pt0.decubing.com/tiny-fellowship/

(Note: there's no "staging" in the URL).

Thanks for the report!
