### ISSUE TITLE
Words disappear into cloud back ground - What we do

### ISSUE THREAD

**Issue by breleha** [4pt0/4pt0-theme#21]
<img width="578" alt="screen shot 2017-08-25 at 11 34 54 am" src="https://user-images.githubusercontent.com/31285256/29723257-7fd82324-8989-11e7-99ec-ef9b4b74fc85.png">

**Comment by bbertucc** [comment]
Thanks @breleha! Definitely a problem. We've reported this on Issue #4 .. Closing this thread. We'll notify ya of the fix on the other issue.
