### ISSUE TITLE
Links - External links take visitors away from site

### ISSUE THREAD

**Issue by breleha** [4pt0/4pt0-theme#22]
Can external links open in a new tab?

**Comment by bbertucc** [comment]
@breleha - yep! I've added that to our list of enhancements.

**Comment by bbertucc** [comment]
@breleha - I added a new checkbox that allows links to appear in new windows. You'll see it whenever you add new buttons.

![screen shot 2017-09-02 at 2 06 43 pm](https://user-images.githubusercontent.com/46652/29998114-35090c7c-8fe8-11e7-8587-57214085e232.png)
