### ISSUE TITLE
Tiny Fellowship - Layout 

### ISSUE THREAD

**Issue by breleha** [4pt0/4pt0-theme#23]
<img width="1440" alt="screen shot 2017-08-25 at 11 45 44 am" src="https://user-images.githubusercontent.com/31285256/29723705-3a5b0850-898b-11e7-8f64-3b2560c01dbe.png">

**Comment by bbertucc** [comment]
@breleha - should be fixed!--> http://4pt0.decubing.com/tiny-fellowship/

In the future, don't go to that staging URL. The proper URL is just `4pt0.decubing.com`
