### ISSUE TITLE
Add form to "Contact Us" page

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#28]

**Comment by raphaelgang** [comment]
what's the best way to integrate the form? we want it to look embedded a la camelback. do you need access to our typeform account? or is that some separate plugin we need?

**Comment by bbertucc** [comment]
We're going to use a WordPress plugin called Gravity Forms — unless you
have another way you want to pull in entries.

Gravity Forms can email someone the form details and also save the form
entry in WordPress.

**Comment by bbertucc** [comment]
@raphaelgang - the contact form is now up: http://4pt0.decubing.com/contact/

You can edit the form under the "Forms" tab in WordPress. There, you can also edit notification settings so that the form data is sent to the proper channels. Once submitted, any form entries will be saved in WordPress
