### ISSUE TITLE
Make Large YouTube videos play within the frame.

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#29]
Currently, YouTube videos pop-out. The team wants YouTube videos to automatically play within the frame.

**Comment by bbertucc** [comment]
@tosbey1 - I wonder if you can create a new themeScript file that does this? Checkout the video at: http://4pt0.decubing.com/essentials-fellowship/

Basically, any link with the class `.single_media_item-item` that had a child div `.item-play_icon` would need to turn into a typical YouTube iFrame, with the video the being whatever is in the `href` attribute.

So, when you clicked ..
```
  <a class="single_media_item-item" href="https://www.youtube.com/watch?v=G_xFo6Hifzk" data-fancybox="gallery-" data-caption="Another sample video.">
    <div class="item-image">
      <img class="image-the_image" src="http://4pt0.decubing.com/wp-content/uploads/2017/07/sample_image-blue-700x525.jpg">
    </div>
    <div class="item-play_icon"></div>
  </a>
```

That element would become..

```
<iframe class="single_media_item-youtube_embed" width="560" height="315" src="https://www.youtube.com/embed/G_xFo6Hifzk" frameborder="0" allowfullscreen></iframe>
```

Note: the class on the iframe.

If you can get the basic replacement functions to work, I'll style it.

You can call the script `themeYouTubeEmbed.js`.

Happy to answer any questions!

**Comment by tosbey1** [comment]
If you'd like I can actually embed the video with wp_oembed_get("link") instead of scripting it.  

With this we could just have the iframe instead of switching from the image to the video. I'm not sure if that is what you wanted though.

**Comment by bbertucc** [comment]
Very cool @tosbey1. Didn't know `wp_oembed_get("link")` existed. I'll update it in the PHP.

**Comment by bbertucc** [comment]
@raphaelgang - moved this to Phase 2 for now, since the feature works this is more of a UX enhancement. Feel free to move it back to Phase 1 or Phase 1 - Critical if you think we need it ASAP.
