### ISSUE TITLE
Add List of Users and Roles

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#30]
Hey @raphaelgang / @CambriaS - We'll need a spreadsheet of all the users you want to add with a column for their roles. 

The current user columns include: username(required), First Name, Last Name, Nickname, email (required), Website, Biographical Info, Job Title (ie- Founder), Facebook URL, Twitter Handle, Role, and "Why did you apply to 4.0?".

Let me know if you have any questions! You can email me the list or upload it here if you want to make it public.

**Comment by raphaelgang** [comment]
Sorry that I forgot to follow up on this. I created a spreadsheet of the teams that we'd like to feature. It includes more data than you had in the list, but we have the information about the city they live in, their photo, and their venture name. Forget how we thought about integrating that into the pages. Feel free to move stuff of the spreadsheet that isn't relevant. Thought it's easier to pull stuff out. 

I haven't finished adding all the facebook links for people, but I'd like to get the batch into the system and batch update the rest as we get closer. 

I don't have quotes yet. It's one of my things to organize and get. We won't have them for everyone. 

The types of users we'll want are 4.0 Team, Tiny Fellows, Launch Fellows, and 4.0 Coaches. I don't have the coaches yet. Where should I go to upload them?

https://docs.google.com/spreadsheets/d/1ZaaNnMSZKha1IM0arALEmTdf9dZ0OFJqCSgPOjRE6q0/edit?usp=sharing

**Comment by raphaelgang** [comment]
@bbertucc how is this going?
