### ISSUE TITLE
Single/Double Columns on Text and Media

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#34]
I'm not sure if it looks bad, but it would be great to have the option to do text in a single column, then media below it. When I click on it now, it looks as if I can switch between single/double column in single media and slideshow, but not the other types. Is that a bug or is that something that shouldn't be there?
![2-screenshot](https://user-images.githubusercontent.com/31212769/29998137-5384b3da-8fe9-11e7-8c1b-cbe80a1e5da4.png)
![1-screenshot 1](https://user-images.githubusercontent.com/31212769/29998136-5382c750-8fe9-11e7-9e7b-e47b3046bfd1.png)

**Comment by bbertucc** [comment]
Text shows up in a single column, with media below it, by default. You should only be able to make text into two columns if you are adding a single media item or slideshow.

If you haven't updated the segment to a two column display and the text is still showing up next to the media, then it's a bug.

**Comment by raphaelgang** [comment]
Makes sense. This is what I'm seeing right now, but just a few minutes ago this same section was positioned below the text and looked great. I don't think I changed anything to the section, but it just moved into this two section view. 
![mosaic two columns ugly](https://user-images.githubusercontent.com/31212769/30003864-328b5f66-908a-11e7-8912-427046f7c968.png)

**Comment by bbertucc** [comment]
Figured out the problem, and Fixed!
