### ISSUE TITLE
Button not a button

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#35]
![button wrong](https://user-images.githubusercontent.com/31212769/29998175-374ca0dc-8fea-11e7-95e5-c0248b938fa2.png)

even though it is a button in the wordpress theme, this is what it looks like on the site.

**Comment by bbertucc** [comment]
Should be fixed, @raphaelgang. We're uploading a bunch of bug fixes today, so you might notice some quirks, like this while the uploads are processing. Also, you might need to refresh your cache (in Chrome: by holding down the shift key and pressing refresh).
