### ISSUE TITLE
Centering and creating a quote

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#37]
I'm trying to create a quote box, similiar to what we have on the User pages, only for a venture. On the venture page for Future Public School, it looks ok, but not so much on the Writebrained one, even though I've formatted them exactly the same way. Not sure what's going on.

![creating a quote writebrained page](https://user-images.githubusercontent.com/31212769/29999384-9646fd50-900b-11e7-97e3-2be9ec11812e.png)

![quote future public schools page](https://user-images.githubusercontent.com/31212769/29999388-b1b9c6ee-900b-11e7-844d-8f1e3a89a3d4.png)

**Comment by bbertucc** [comment]
Hmm.. are you entering in all the content into the Title area?

I would suggest adding it to the subtitle or body area.

You can recreate the quote box by entering text into the subtitle area and
adding the watercolor background to the segment.
