### ISSUE TITLE
Creating text above form

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#38]
Would love to put a short note above the form like this one. How do I do that?
![text above form](https://user-images.githubusercontent.com/31212769/29999684-fa622916-9017-11e7-8bf9-e7435b3bf284.png)

**Comment by bbertucc** [comment]
On the "Contact" page, you can add text above the form short code. I added text and a horizontal line to demo it.

**Comment by raphaelgang** [comment]
ah makes sense that that is separate from the form itself.  





On Sun, Sep 3, 2017 11:10 AM, Blake Bertuccelli notifications@github.com  wrote:
On the "Contact" page, you can add text above the form short code. I added text
to demo it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by raphaelgang** [comment]
is there a way to put language under the Contact heading?

**Comment by bbertucc** [comment]
Not sure I'm following?... you can add text right on the contact page,
above or below the shortcode for the form.
