### ISSUE TITLE
Grid with more than 4 photos

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#39]
When I have 3 photos, the grid posts the photos below the text. 
![grid with 3 photos](https://user-images.githubusercontent.com/31212769/30003586-71b9d82a-9085-11e7-8f3d-71343841175e.png)

But when I have more than 3 photos, the grid posts the photos to the side of the text and the photos are small.
![grdi with more than 4 photos on side](https://user-images.githubusercontent.com/31212769/30003579-5723d42a-9085-11e7-92e3-5f8f8da15921.png)

How do I get it to look like what you have on the example page, only with text above the pics?
![media grid](https://user-images.githubusercontent.com/31212769/30003597-905316ca-9085-11e7-8b00-e998de89b8c2.png)

**Comment by raphaelgang** [comment]
I just added more boxes to that section and now it looks the right way. Maybe it only does that for up to 4 boxes. 
![more boxes](https://user-images.githubusercontent.com/31212769/30003878-6b5b3924-908a-11e7-8a68-1b627d38d8c1.png)

**Comment by bbertucc** [comment]
Fixed! Now, you should be able to add as few or as many boxes as you want without changing sizes.
