### ISSUE TITLE
Mosaic and Orange Background

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#40]
![mosaic on orange](https://user-images.githubusercontent.com/31212769/30003782-be02f998-9088-11e7-91d7-4e62e4259bdf.png)

Should it just not be an option? Or is it possible to have us control the color of the mosaic buttons besides adding a photo?

**Comment by bbertucc** [comment]
I'm not too crazy about the orange background all together. Too in your face. Would you feel a loss if we got rid of it?

**Comment by raphaelgang** [comment]
not at all. i was having a hard time finding a place to use it. I think it
works best as buttons. If you look at our current site, that's the only way we
use it currently.  





On Sun, Sep 3, 2017 10:52 AM, Blake Bertuccelli notifications@github.com  wrote:
I'm not too crazy about the orange background all together. Too in your face.
Would you feel a loss if we got rid of it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
