### ISSUE TITLE
Timeline feature

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#41]
We talked about it a while ago, but realized I didn't add it here as a request. 

![screenshot 2017-09-03 at 11 50 41 am](https://user-images.githubusercontent.com/31212769/30004976-2524bf48-909e-11e7-9910-36d2c2aecf83.png)

**Comment by bbertucc** [comment]
Totally forgot about this! Good to have it on the to do list.

**Comment by bbertucc** [comment]
Hey @raphaelgang - The Timeline segment is now up!

You can add a timeline segment to any page the same way you would add a text or media segment. 
<img width="643" alt="screen shot 2017-11-16 at 5 27 15 pm" src="https://user-images.githubusercontent.com/46652/32919349-7e4d6978-caf3-11e7-9c62-24f87810ef65.png">

I created this demo for you to click around and play with: https://4pt0.org/timeline-examples/

The features will scale to mobile.
