### ISSUE TITLE
External Links Automatically Open New Tab

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#46]
There's a bunch of instances where we'll want to include external links, but it looks like there isn't that button that allows me make it open in a new tab. Is it possible to make that a universal default? I'd want it to apply to the social buttons and pretty much everything that doesn't send someone to an internal site. 
![external link](https://user-images.githubusercontent.com/31212769/30138993-f1e1d004-9330-11e7-9cd4-6786c0c41df4.png)

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
