### ISSUE TITLE
PDF 

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#48]
When I look to add a pdf, it asks me for a website link to it, but I'm not sure what I should put in the square. I inserted a link to google drive that included a pdf, but it didn't show anything. What steps should I take to upload a pdf so it appears correctly?
![pdf upload](https://user-images.githubusercontent.com/31212769/30143627-815282a4-934c-11e7-8827-2ec95b09abb9.png)

 
![pdf](https://user-images.githubusercontent.com/31212769/30143615-6603a6a4-934c-11e7-9637-3b8908733871.png)

**Comment by bbertucc** [comment]
@raphaelgang - In the link area, you'll have to put link to the PDF file itself. The google drive file is technically not a pdf. You can upload the PDF to the website under the Media tab in WordPress, then replace the google drive URL with the URL that WordPress gives you. That should work!

**Comment by raphaelgang** [comment]
So helpful. Yes that worked!  





On Thu, Sep 7, 2017 10:02 AM, Blake Bertuccelli notifications@github.com  wrote:
@raphaelgang  - In the link area, you'll have to put link to the PDF file
itself. The google drive file is technically not a pdf. You can upload the PDF
to the website under the Media tab in WordPress, then replace the google drive
URL with the URL that WordPress gives you. That should work!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by bbertucc** [comment]
Sweet!
