### ISSUE TITLE
Youtube Video Loading Very Slow

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#49]
It took over a minute to load a video and it hadn't even started playing when I stopped it. The video was only a 30 second video as well. 

![youtube loading slow](https://user-images.githubusercontent.com/31212769/30143689-d792d02e-934c-11e7-8b2b-5b5b4dbe177f.png)

**Comment by bbertucc** [comment]
@raphaelgang Is the youtube still loading slowly for you? Working fine for me.

**Comment by raphaelgang** [comment]
realized that an extension that i have was interfering with it. we're good.  





On Fri, Sep 8, 2017 5:06 PM, Blake Bertuccelli notifications@github.com  wrote:
@raphaelgang  Is the youtube still loading slowly for you? Working fine for me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
