### ISSUE TITLE
Drop Down Menus in Menu Bar

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#50]
may be very helpful.

**Comment by raphaelgang** [comment]
I know we marked this as a phase two thing, but if it's possible to get it in before thursday, it would be awesome. Getting lots of feedback from the team about how helpful it would be in terms of navigating the site and I'm realizing it's hard to go back and forth on the pages.

**Comment by bbertucc** [comment]
This is a big UX shift. Dropdowns don't really work well on touch devices. I strongly recommend dedicating time to UX design instead of just slapping on some dropdowns, but if we can't I understand.

**Comment by raphaelgang** [comment]
Ideally it would look similar to what camelback has on their mobile site. Is
that possible?  





On Tue, Sep 12, 2017 10:52 AM, Blake Bertuccelli notifications@github.com 
wrote:
This is a big UX shift. Dropdowns don't really work well on touch devices. I
strongly recommend dedicating time to UX design instead of just slapping on some
dropdowns, but if we can't I understand.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by bbertucc** [comment]
Sure, we'll jump on it. ... But I hope we can refine the UX in Phase 2 (see issue #87).

**Comment by bbertucc** [comment]
Forgot to tell ya, you can add dropdowns now...
<img width="745" alt="screen shot 2017-09-13 at 8 11 05 pm" src="https://user-images.githubusercontent.com/46652/30407765-e37d12c8-98bf-11e7-8266-871ef761c2cc.png">

To create a dropdown in WordPress, click the Menus link under the appearance tab. Drag a page under another page, and voila!

<img width="546" alt="screen shot 2017-09-13 at 8 13 19 pm" src="https://user-images.githubusercontent.com/46652/30407791-09f26af2-98c0-11e7-9f9a-819034922a03.png">

**Comment by raphaelgang** [comment]
I tried to do this and it didn't look that way for me. here's what i saw  
1-capture.gif 7MB  Download 





On Wed, Sep 13, 2017 8:13 PM, Blake Bertuccelli notifications@github.com  wrote:
Forgot to tell ya, you can add dropdowns now...


To create a dropdown in WordPress, click the Menus link under the appearance
tab. Drag a page under another page, and voila!



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by raphaelgang** [comment]
i just tried it again. it looked good on the homepage, but when i went to the Tiny/Essentials pages it didn't work right. it wouldn't let me scroll onto the second menu item and the menu would close really quickly. see the gif below.
![1-capture 1](https://user-images.githubusercontent.com/31212769/30411657-fb54d198-98d7-11e7-8363-d9544bc0ae30.gif)

**Comment by bbertucc** [comment]
Hey @raphaelgang - Dropdowns should be fixed. Test it out and close this issue if it works. Sorry about the bug!

**Comment by raphaelgang** [comment]
Yes, just tested it and the look good. Thanks!  





On Thu, Sep 14, 2017 10:09 AM, Blake Bertuccelli notifications@github.com 
wrote:
Hey @raphaelgang  - Dropdowns should be fixed. Test it out and close this issue
if it works. Sorry about the bug!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
