### ISSUE TITLE
Ability to have different pages highlighted in header and footer

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#51]
It would be really great to be able to feature slightly different set of pages on the head and footer. 
![bukket_1_4-screenshot](https://user-images.githubusercontent.com/31212769/30188680-70fe726a-93f5-11e7-9e56-4bf7ab18ba11.png)
![bukket_0_3-screenshot](https://user-images.githubusercontent.com/31212769/30188681-71021348-93f5-11e7-9118-16fcd0565114.png)

**Comment by bbertucc** [comment]
Now you can!

In WordPress, under Appearance, click "Menus".

You can create a new menu and select it to display on the footer.

![screen shot 2017-09-08 at 4 11 58 pm](https://user-images.githubusercontent.com/46652/30231440-7ab28876-94b0-11e7-9ee2-89c94c7d1d06.png)
