### ISSUE TITLE
Portrait/Landscape Not showing

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#53]
On the Mindright Venture page, the portrait/landscape picture isn't working. It's got the pic to the side but there's no pic.
![2-screenshot 1](https://user-images.githubusercontent.com/31212769/30211041-df69ef58-9464-11e7-9a98-c3afcd465502.png)
![executing pilot](https://user-images.githubusercontent.com/31212769/30211040-df67c976-9464-11e7-8104-b82aee000bcd.png)

What I think I just noticed is that the point when it has an issue with this is when I switch it from one type of photo layout to another. Prior to this, it was in a single picture mode, but when I switched it, it didn't convert right. But if I just created  a new section, it looked like it was working correctly. I think I've been having this problem for pretty much anytime I'm switching between photos to the side of text and photos below. This may explain why I've been having so many issues getting the pictures loaded.

**Comment by bbertucc** [comment]
@raphaelgang - fixed. Had to delete some settings saved from an older iteration of the theme.
