### ISSUE TITLE
Connect Google Analytics to new site

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#54]
Blake, what do you need from me in order to get our google analytics connected to the new site?

**Comment by bbertucc** [comment]
I just added an update that will allow you to put footer and header embed codes in yourself.

In WordPress, under the Appearance tab, click "Customize". There you should see an "Embed Codes" section (pictured). I believe the Google Analytics code needs to be in the header.

![screen shot 2017-09-08 at 12 34 30 pm](https://user-images.githubusercontent.com/46652/30223844-1c07ffe0-9492-11e7-8aa6-8c59a47e312a.png)
