### ISSUE TITLE
Connect Facebook Pixel to new website

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#55]
Blake, what do you need from us to get the Facebook pixel set up on the new site?

**Comment by bbertucc** [comment]
Checkout my answer to Issue #54 .. You can add any tracking codes you need in WordPress, under the Appearance > Customize link.

**Comment by bbertucc** [comment]
The pixel has been added. For future reference, administrators can add or edit these embed codes under the Appearance tab > Customize > Embed Codes
