### ISSUE TITLE
Redirects for the previous website

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#56]
Blake, what should we be doing in terms of doing redirects for the old site so that we don't have pages that people get stuck on?

**Comment by bbertucc** [comment]
I'm not quite following.. Can you give me an example?

**Comment by raphaelgang** [comment]
Our current website has pages that will be deactivated - basically the stuff that's on the first part of this blog http://searchengineland.com/relaunching-site-dont-even-think-without-solid-seo-game-plan-231315

should Gerrish be doing this?

**Comment by bbertucc** [comment]
This would be a Gerrish thing. I'm available to help if needed.
