### ISSUE TITLE
Homepage/ Click on Our Fellowships

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#57]
When I go on mobile and click on the Our Fellowships mosaic button on the homepage, it takes me to a blank page. It doesn't do this on desktop though. Both in chrome.

**Comment by bbertucc** [comment]
I'm having trouble recreating this error. Can you try it again in a private browsing window? If the error persists, let me know what device model you're looking at it on. If the link works in the private browsing window, you might need to clear your cache.

**Comment by raphaelgang** [comment]
yep works in private browser. good to go.  





On Fri, Sep 8, 2017 12:47 PM, Blake Bertuccelli notifications@github.com  wrote:
I'm having trouble recreating this error. Can you try it again in a private
browsing window? If the error persists, let me know what device model you're
looking at it on. If the link works in the private browsing window, you might
need to clear your cache.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
