### ISSUE TITLE
Portrait/Landscape Photos on Ventures Pages

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#58]
This is from portrait/landscape photos on the writebrained page
![1-screenshot 4](https://user-images.githubusercontent.com/31212769/30239599-09e7a628-9526-11e7-92ec-4aea4de9c11b.png)

**Comment by bbertucc** [comment]
Got it. Will take care of it. (Funny to see you up at dawn thinking about
the site too — must be getting close to launch.)

**Comment by bbertucc** [comment]
Fixed.
