### ISSUE TITLE
Do you want links without images to look like buttons?

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#59]
I can easily make these, and every other link that doesn't have an image, look like a button. Would that help?
![screen shot 2017-09-09 at 6 27 27 am](https://user-images.githubusercontent.com/46652/30239716-232a8414-9528-11e7-8478-efbfb1d06302.png)

**Comment by raphaelgang** [comment]
It would be great to have some sort of option for when we want multiple buttons. I was planning to just add photos, but I've noticed a bunch of instances where I need multiple buttons in a section.

**Comment by bbertucc** [comment]
I like what you did on WriteBrained. Will work on something link this.
![screen shot 2017-09-09 at 7 26 21 am](https://user-images.githubusercontent.com/46652/30240131-575386a2-9530-11e7-8147-89bb55321152.png)

**Comment by bbertucc** [comment]
Added this to Phase 2 work .. it's not a lot of work, but if you found a work around might be smart to focus my time elsewhere. Happy to adjust if you like.

**Comment by bbertucc** [comment]
Disregard my last comment.. This can be easily done for Phase 1.

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
