### ISSUE TITLE
Entire section of pics not showing up on Writebrained page

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#62]
Probably similar to the other bugs on this page where photos aren't showing up, but this entire section (Interested?) of a grid just isn't showing up
![2-screenshot 2](https://user-images.githubusercontent.com/31212769/30239956-980f3546-952c-11e7-84e2-9970349b338d.png)
![1-screenshot 7](https://user-images.githubusercontent.com/31212769/30239955-980d1b30-952c-11e7-95f1-637404021181.png)

**Comment by bbertucc** [comment]
Fixed.
