### ISSUE TITLE
Is there a way to embed a map?

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#63]
Would love to be able to embed a map to our office. Understand if this is something for later.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3457.1262048281087!2d-90.07102478505905!3d29.947048281917702!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8620a673bd89fb51%3A0xb2a3e1947021328d!2s4.0+Schools!5e0!3m2!1sen!2sus!4v1504961092563" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

**Comment by bbertucc** [comment]
Definitely a good idea. We would need to redevelop the media segment a bit to enable embed codes. Saving this to "Phase 2," but probably can get to it soon after Monday.
