### ISSUE TITLE
User Page for Team Member

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#64]
Two things:
1. Can we make it so that Administrator doesn't show up as a tag on the user pages. Would be confusing for the public side of things.

2. I can't find a way to load a photo for a user. How do I do that?

What's the best way to get the team's information onto the site?

![1-screenshot 8](https://user-images.githubusercontent.com/31212769/30240410-ad3b30ce-9535-11e7-8c70-6df079ee1fe7.png)

**Comment by bbertucc** [comment]
1- Yes.

2. WordPress uses gravitars for user photos. https://en.gravatar.com -
perhaps we'll need to use a solution where you can upload the photo instead?

**Comment by raphaelgang** [comment]
Great. 

Yes, I would like to be able to upload photos of people, not have it pull from some other source.

**Comment by bbertucc** [comment]
Fixed this.
