### ISSUE TITLE
Content Not Showing on Apply Page

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#65]
There should be a grid that is showing here and the subtitle isn't centered. 
![1-screenshot 9](https://user-images.githubusercontent.com/31212769/30241621-9c8eb194-954c-11e7-9a4a-196cdacce53e.png)

**Comment by raphaelgang** [comment]
I tried to move the content and it did the same thing again. 

![1-screenshot 14](https://user-images.githubusercontent.com/31212769/30253825-838d78ae-9652-11e7-95b3-cc07b25f59fd.png)

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
