### ISSUE TITLE
Text Sizes Not Differentiating

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#66]
When I create the FAQ page, it seems like all the text sizes are the same sizes, so it's hard to create visual hierarchy. Am I missing something or is that something to be fixed?

![1-screenshot 10](https://user-images.githubusercontent.com/31212769/30241686-f564bd9e-954d-11e7-9b09-08d258be2339.png)

**Comment by bbertucc** [comment]
note to self: update the get involved look when the text sizes are conformed.

**Comment by bbertucc** [comment]
Fixed.
