### ISSUE TITLE
Newsletter page?

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#69]
How can i create a page that just has our newsletter sign up form on it? I want a page called 4pt0.org/newsletter that just has our mailchimp embedded on it.

**Comment by bbertucc** [comment]
Moved this to phase 2. Let me know if you need it sooner. Will have to do some custom design work.

**Comment by raphaelgang** [comment]
Is the newsletter sign up going to work? right now it's not. that is critical.
I'm also ok if the design isn't perfect. I just want to make it easy for people
to sign up.  





On Tue, Sep 12, 2017 10:41 AM, Blake Bertuccelli notifications@github.com 
wrote:
Moved this to phase 2. Let me know if you need it sooner. Will have to do some
custom design work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by bbertucc** [comment]
Cool. We will get it up and working.

**Comment by bbertucc** [comment]
Done: http://4pt0.decubing.com/newsletter/
