### ISSUE TITLE
blurry pictures

### ISSUE THREAD

**Issue by tevintc** [4pt0/4pt0-theme#7]
hey I don't know why but when I uploaded a picture they appeared blurry, what can I do to change that? the picture are high resolution.

**Comment by bbertucc** [comment]
@tevintc - you found a bug! Can you add a screenshot of the page you see the blurry picture on? Taylor or I will fix it.

**Comment by bbertucc** [comment]
@tosbey1 - Try to just load in a larger version of the image instead of doing any CSS/HTML changes. Documentation: https://www.advancedcustomfields.com/resources/image/

**Comment by bbertucc** [comment]
@tevintc - Pictures should be looking good. Make sure you upload pictures with dimensions larger than 1200px by 1200px.
