### ISSUE TITLE
Text not formatting correctly

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#71]
This is supposed to be subtitle and text is centered like the other sections.
![1-screenshot 13](https://user-images.githubusercontent.com/31212769/30244215-72261f90-957f-11e7-8e82-e8a4c36820aa.png)

**Comment by bbertucc** [comment]
What page is this?

**Comment by raphaelgang** [comment]
this is the FAQ page.

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
