### ISSUE TITLE
Images in two column format on mobile

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#73]
photos are like this in a bunch of places on the site. on chrome.
![369dd4a9-c4d7-4971-8a2c-bab4546a4780](https://user-images.githubusercontent.com/31212769/30244251-62c2efa0-9580-11e7-9fe8-d0b3c8b0b0a0.PNG)

**Comment by bbertucc** [comment]
That's by design, but I will have them scale to a new line.

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
