### ISSUE TITLE
header menu on mobile

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#74]
is there a way to put this below the logo?
![192c1fb4-ab62-4f77-8ae9-0d5664ff0e74](https://user-images.githubusercontent.com/31212769/30244260-8140225e-9580-11e7-8720-aaef8f7c5e51.PNG)

**Comment by bbertucc** [comment]
Not a good idea to put the menu below the logo. You'll loose valuable view port space, especially on phones smaller than yours. I can convert the navigation button to just the hamburger bars, so that it doesn't interfere.

**Comment by bbertucc** [comment]
Made the mobile nav a solo hamburger.
