### ISSUE TITLE
Buttons on Referral Form page still small

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#77]
![1-screenshot 16](https://user-images.githubusercontent.com/31212769/30283272-3e7e3600-96dd-11e7-8e46-48fa11c734b2.png)

**Comment by bbertucc** [comment]
Updated.
![screen shot 2017-09-12 at 9 13 58 pm](https://user-images.githubusercontent.com/46652/30356572-52c655fc-97ff-11e7-9aef-ec6e26d5c0e5.png)
