### ISSUE TITLE
User Page: cloud text sequence

### ISSUE THREAD

**Issue by CambriaS** [4pt0/4pt0-theme#8]
![screen shot 2017-08-23 at 10 30 52 am](https://user-images.githubusercontent.com/31285237/29625581-bfb08d2c-87f1-11e7-88dd-fb99d5a9fc5c.png)

Bug line and clouds are coming after the block of text about the test user

**Comment by bbertucc** [comment]
@tosbey1 - To resolve, you can probably delete any reference of `print_r()` from the template_part.
