### ISSUE TITLE
Loading on mobile is slow

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#80]
When Ioad pages on mobile (chrome on an iphone), it loads really slowly and parts of each page won't load for several seconds, then appear. There will be a white space where it's supposed to be then a few seconds later it will appear. It wasn't doing this in previous versions of the site.

**Comment by bbertucc** [comment]
I think this issue is related to #79.

**Comment by bbertucc** [comment]
Collapsed this issue into Issue #86.
