### ISSUE TITLE
multiple pages include wpengine in address bar

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#88]
looks like something weird happens when you go to the contact us page, though page seems to be working.

**Comment by raphaelgang** [comment]
other pages doing it
refer
share
apply
essentials
tiny
faqs
events

it also looks like this is causing the site to open new tabs when you click on the grid menu i created at the bottom of essentials/tiny/fellowships pages.

**Comment by raphaelgang** [comment]
ok, i went through the site and think i found all the links that were sending people to the wrong place and fixed them. it looked like some weird thing related to the conversion since all the links had fourptoh.wpengine in them. 

the ones i can't figure out are the ones for the mosaic on the homepage. it sends you to the right page on the site, but it has a weird address in the address bar. and since the mosaic doesn't require a link for pages inside the site, i'm not sure how to update it.  just click on any of the pieces in the mosaic.

**Comment by raphaelgang** [comment]
and many of the links, especially the ones in the grid menu at the bottom of the tiny/essentials/fellowships pages open new tabs with every link you click.

**Comment by bbertucc** [comment]
This should be resolved now that the site is on a new server.
