### ISSUE TITLE
Mobile Updates

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#96]
- Update Media for mobile.
- Improve Speed.
- Make content fit in mobile browser better.

**Comment by bbertucc** [comment]
Hey @raphaelgang -

The mobile updates are up. I fixed the problems with grid content, updated the way content responds to the browser window, and optimized the style to minimize load times.

Let me know if you see any errors or need anything else.

**Comment by raphaelgang** [comment]
Overall looks great. Couple of small things. 

1)it looks like in mobile, depending on wehther the photo is on the left or right of content, it shows up in a different order. Can we make it consistent?  
![mobile issue arranges content](https://user-images.githubusercontent.com/31212769/32959714-23c6ba28-cb88-11e7-9030-522f0c8695a1.png)


2) When I've made the photos as buttons, I think it actually looks better if they just become bigger photos the way they are on the home page (in mobile). Can you shift those? 
![img_56bc79531a4d-1](https://user-images.githubusercontent.com/31212769/32959805-68159384-cb88-11e7-9d64-d8856fb5932b.jpeg)

![img_ae31ce6f40eb-1](https://user-images.githubusercontent.com/31212769/32959771-54614b9e-cb88-11e7-8eec-4a4b82a475bd.jpeg)

Other than that, it looks good.

**Comment by bbertucc** [comment]
Hey @raphaelgang - I updated the order of the two column content on mobile. Take a look! (Make sure you delete your cache or view in a private browser.)
