### ISSUE TITLE
Community Page not fully loading

### ISSUE THREAD

**Issue by raphaelgang** [4pt0/4pt0-theme#98]
The community page isn't loading all the users. It just stops after the first 16 or so people on the page. 
![communitypage](https://user-images.githubusercontent.com/31212769/38257311-9ba8fb56-3725-11e8-86ad-06ab18e9b11f.png)

**Comment by bbertucc** [comment]
Hmm - what browser are you on? Everything is working great for me:

![lzrpjpdiig](https://user-images.githubusercontent.com/46652/38262727-bedccfd6-3733-11e8-87e5-3a1a495ad265.gif)

**Comment by raphaelgang** [comment]
chrome. weird. i just tested in incognito mode and it's working right.
guess i just needed to clear my cache.

**Comment by bbertucc** [comment]
Glad to hear it!
